# Generated by Django 3.1.3 on 2020-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kwic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='输入内容')),
                ('result', models.TextField(verbose_name='处理结果')),
            ],
            options={
                'verbose_name': 'KWIC处理',
                'verbose_name_plural': 'KWIC处理',
            },
        ),
    ]
